apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: muchtodo
type: Opaque
# Values are base64-encoded: admin -> YWRtaW4=, adminpassword -> YWRtaW5wYXNzd29yZA==
data:
  mongo-root-username: YWRtaW4=
  mongo-root-password: YWRtaW5wYXNzd29yZA==
