#!/bin/sh
set -e

cat > /app/.env <<EOF
PORT=${PORT:-8080}
MONGO_URI=${MONGO_URI}
DB_NAME=${DB_NAME:-much_todo_db}
JWT_SECRET_KEY=${JWT_SECRET_KEY}
JWT_EXPIRATION_HOURS=${JWT_EXPIRATION_HOURS:-72}
ENABLE_CACHE=${ENABLE_CACHE:-false}
REDIS_ADDR=${REDIS_ADDR:-}
REDIS_PASSWORD=${REDIS_PASSWORD:-}
LOG_LEVEL=${LOG_LEVEL:-INFO}
LOG_FORMAT=${LOG_FORMAT:-json}
EOF

exec /app/server
