apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: muchtodo
type: Opaque
# JWT_SECRET_KEY base64: bXktc3VwZXItc2VjcmV0LWp3dC1rZXk= = my-super-secret-jwt-key
# MONGO_URI base64-encoded connection string
data:
  jwt-secret-key: bXktc3VwZXItc2VjcmV0LWp3dC1rZXk=
  mongo-uri: bW9uZ29kYjovL2FkbWluOmFkbWlucGFzc3dvcmRAbW9uZ29kYi1zZXJ2aWNlOjI3MDE3L211Y2hfdG9kb19kYj9hdXRoU291cmNlPWFkbWlu
